### ISSUE TITLE
Possible feature enhancements.

### ISSUE THREAD

**Issue by divy9881** [AliabbasMerchant/GetFolderFromRepo#1]
- Allow downloading multiple folders by supporting multiple command line args
- Allow an option to enter into interactive mode by using ```flag (-i)``` to download multiple folders or files. This option will be particularly helpful when a user wants to get too many folders, which will not be convenient enough to type their paths as command-line args.

I will be happy to tackle this issue in a day or two, but if you want you can do it.

**Comment by AliabbasMerchant** [comment]
So, the first one would be like, `getFolderFromRepo.py link1 link2 link3`?  
We can definitely do this. Should be simple enough.

What would be the expected 'flow' for the 2nd point? Can you show some example?

**Comment by divy9881** [comment]
For ex:
```getFolderFromRepo.py -i <repo_link> (<branch_name>)```
If the repo link and branch name(which is optional) is valid then control enters into some-what REPL mode where in you can allow the user to query contents of the repository or a specific folder, show branches, download some files or folders from the repository and maybe allow auto-completion of file or folder names by pressing tab.

**Comment by AliabbasMerchant** [comment]
Okay.  
Take it up if you want to.

**Comment by divy9881** [comment]
Sure.
